import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

 export const products = [
  {
    _id: uuid(),
    title : "U.S POLO ASSN.",
    discount : "50%",
    image : "/assets/images/model1.jpg",
    price : 899,
    rating : 4,
    category : {fastDelivery : true, arrivingSoon : true, productType : "Men"},
    name : "Denim Jacket",
    homeVisibility : true
  },
  {
    _id: uuid(),
    title : "VERA MODA",
    discount : "30%",
    image : '/assets/images/modal2.jpeg' ,
    price : 599,
    rating : 4,
    category : {fastDelivery : false, arrivingSoon : true, productType : "Men"},
    name : "Fit Checked Shirt",
  },
  {
    _id: uuid(),
    title : "JACK&JONES",
    discount : "60%",
    image : '/assets/images/modal3.jpg' ,
    blonging : true,
    collection : "Winter Collection",
    arivalText : "New Arrival",
    text : "Checkout our best winter Collection to stay hot in style this season.",
    price : 999,
    rating : 3,
    category : {fastDelivery : true, arrivingSoon : false, productType : "Men"},
    name : "Formal Blazer",
  },
  {
    _id: uuid(),
    title : "TOMMY HILFIGER",
    discount : "40%",
    image : '/assets/images/model4.jpg' ,
    blonging : true,
    collection : "Summer Collection",
    arivalText : "New Arrival",
    text : "Checkout our best summer Collection to stay cool in style this season.",
    price : 789,
    rating : 5,
    category : {fastDelivery : false, arrivingSoon : true, productType : "Men"},
    name : "Cotton T-shirt",
    homeVisibility : true
  },
  {
    _id: uuid(),
    title : "Manyavar",
    discount : "60%",
    image : '/assets/images/female-model1.webp' ,
    price : 855,
    rating : 4,
    category : {fastDelivery : true, arrivingSoon : true, productType : "Women"},
    name : "Ethinc Motifs Kurta",
  },
  {
    _id: uuid(),
    title : "DRESS BERRY",
    discount : "35%",
    image : '/assets/images/female-model2.webp' ,
    price : 679,
    rating : 4,
    category : {fastDelivery : false, arrivingSoon : true, productType : "Women"},
    name : "Floral Printed Kurta",
    homeVisibility : true
  },
  {
    _id: uuid(),
    title : "ANOUK",
    discount : "10%",
    image : '/assets/images/female-model3.webp' ,
    collection : "Winter Collection",
    price : 1249,
    rating : 2,
    category : {fastDelivery : true, arrivingSoon : false, productType : "Women"},
    name : "Yoke Design Kurta",
  },
  {
    _id: uuid(),
    title : "ONLY",
    discount : "20%",
    image : '/assets/images/female-model4.webp' ,
    collection : "Summer Collection",
    price : 1679,
    rating : 2,
    category : {fastDelivery : true, arrivingSoon : true, productType : "Women"},
    name : "Sriped Straight Kurta",
    fastDelivery : true,
    arrivingSoon : true,
  },
  {
    _id: uuid(),
    title : "TOMMY HILFIGER",
    discount : "60%",
    image : '/assets/images/kid-model1.jpeg' ,
    price : 749,
    rating : 4,
    category : {fastDelivery : true, arrivingSoon : false, productType : "Kids"},
    name : "Girls Cotton T-shirt",
  },
  {
    _id: uuid(),
    title : "H&M",
    discount : "35%",
    image : '/assets/images/kid-model2.webp' ,
    price : 984,
    rating : 1,
    category : {fastDelivery : false, arrivingSoon : true, productType : "Kids"},
    name : "Boys Black Jeans",
  },
  {
    _id: uuid(),
    title : "MANGO KID",
    discount : "10%",
    image : '/assets/images/kid-model3.webp' ,
    collection : "Winter Collection",
    price : 1170,
    rating : 3,
    category : {fastDelivery : true, arrivingSoon : true, productType : "Kids"},
    name : "Pocket T-shirt",
    homeVisibility : true
  },
  {
    _id: uuid(),
    title : "MARKS AND SPENCER",
    discount : "20%",
    image : '/assets/images/kid-model4.webp' ,
    collection : "Summer Collection",
    price : 680,
    rating : 1,
    category : {fastDelivery : true, arrivingSoon : false, productType : "Kids"},
    name : "Viscose Dress",
  }
];

